### ISSUE TITLE
Widget AndroidAppPromotion - CSS bugy

### ISSUE THREAD

**Issue by xurban42** [seznam/JAK#132]
1 . Widget - AndroidAppPromotion

Android Chrome 36.0.1985.131
ak je nastaveny background na html elemente:

``` html
<span class="stars" style="/* background: url(/st/img/androidAppPromotion/star.png) 0 0 repeat; */"></span>
```

tak sa ignoruje vlastnost v triede:

``` css
.appPromotion .apInfo .stars {
    ...
    background-size: 14px auto;
    ...
}
```

Preto by bolo vhodne doplnit napr. !important flag:

``` css
.appPromotion .apInfo .stars {
    ...
    background-size: 14px auto !important;
    ...
}
```

---

2 . Obcas sa neda spolahnut na to, že text s info bude zarovnany vlavo. 

Preto by bolo vhodne do CSS pridat:

``` css
.appPromotion .apInfo {
    ...
    text-align: left;
}
```
